-- ================================================================
-- Import élèves saison 2025-2026
-- Généré le 2026-04-24 · 164 élèves · 167 inscriptions
-- À exécuter dans l'éditeur SQL de Supabase
-- ================================================================

-- Notes de déduplication :
-- Couples partageant un même email (1 seul compte créé, l'autre partenaire n'a pas de login) :
--   hbutash@gmail.com          : Henry BUTASH & Irmak NACAK
--   salvaje91@gmail.com        : Hugo FIGUEREDO & Anais GOSSELIN
--   p.sabrier@gmail.com        : Pauline SABRIER & Bruno GODEFROY
--   paminaetemmanuel@gmail.com : Pamina & Emmanuel PERES DE HAUTECLCOCQUE
--   locvinchau@gmail.com       : Ambroise & Clothilde SCHALCHLI
--   lesvorms@noos.fr           : Sandrine & Bertrand VORMS
--   maria.karadjova@dentons.com: Maria KARADJOVA & Nikolay KARADJOV
-- → Ces 7 couples devront créer 2 comptes séparés pour que chacun ait un accès.
--
-- Inscriptions multi-cours :
--   flocastagnos@yahoo.fr : Florence Castagnos inscrite débutant + intermédiaire
--   vvasiliu@gmail.com    : Vlad Vasiliu inscrit paris + vincennes
--   sandrine_billot@...   : Sandrine Billot inscrite hatha + yin

BEGIN;

-- 1. ÉLÈVES (164 entrées uniques)
-- ----------------------------------------------------------------
INSERT INTO eleves
  (nom, prenom, email, tel, niveau, ville, statut_eleve, source,
   partenaire, email_partenaire, notes, saison,
   carte_date_achat, carte_expiration, carte_utilises, carte_restants,
   carte_statut, carte_paye)
VALUES
  ('ALAMI', 'Hicham', 'hicham.a85@icloud.com', '+33613412690', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('ALLIX', 'Louise', 'allix.louise.l@gmail.com', '+33680838698', 'debutant', 'paris', 'Actif', 'inscription', 'Elizabeth Lombrey', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('ANGHEL', 'Serban', 'serbanghel@gmail.com', '+33626625658', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('AUCORDIER', 'Jérôme', 'jaucordier@colibri-asso.fr', '+33618766458', 'debutant', 'paris', 'Actif', 'inscription', 'Anouch SARAFIAN', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('AYAD', 'Christophe', 'christophe.ayad@gmail.com', '+33675235619', 'debutant', 'paris', 'Actif', 'inscription', 'Olivia Colo', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BEZIN', 'Alexandre', 'alexandre-bezin@orange.fr', '+33650305005', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('BOUAZIZ', 'Thouraya', 'bouazizthou@live.fr', '+33623827662', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('BUTASH', 'Henry', 'hbutash@gmail.com', '+33695971993', 'debutant', 'paris', 'Actif', 'inscription', 'Irmak Nacak', '', 'email partagé avec: Irmak NACAK', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('CARDINET', 'Rémy', 'remy.cardinet+tango@gmail.com', '+33619185739', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('CASTAGNOS', 'Florence', 'flocastagnos@yahoo.fr', '+33629735791', 'intermediaire', 'paris', 'Actif', 'inscription', '', '', 'niveaux: debutant + intermediaire', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('COLO', 'Olivia', 'oliviacolo@gmail.com', '+33683250746', 'debutant', 'paris', 'Actif', 'inscription', 'Christophe Ayad', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('COSENTINO', 'Clara', 'claracosentino1306@gmail.com', '+33776924440', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('DAMY', 'Ameline', 'ameline.damy@gmail.com', '+33652372879', 'debutant', 'paris', 'Actif', 'inscription', 'Benoît Piketty', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('DIAZ', 'Felipe', 'felipea.diazp@gmail.com', '+33783531142', 'debutant', 'paris', 'Actif', 'inscription', 'Angèle Diaz', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('DUVAL-GALVAN', 'Laurence', 'lgdg5924@gmail.com', '+33681084160', 'debutant', 'paris', 'Actif', 'inscription', 'Jorge Galvan', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('EYRAUD', 'Marine', 'marineeyraud@yahoo.fr', '+33789023573', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('FIGUEREDO', 'Hugo', 'salvaje91@gmail.com', '+33674891945', 'debutant', 'paris', 'Actif', 'inscription', 'ANAIS GOSSELIN', '', 'email partagé avec: Anais GOSSELIN', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('FOFANA', 'Aïcha', 'f.aicha@yahoo.fr', '+33619968476', 'debutant', 'paris', 'Actif', 'inscription', 'Guarino Gautier', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('FONTAINE', 'Nicolas', 'nicolas.fontaine@gmx.com', '+33676343337', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('GALVAN', 'Jorge', 'georges.galvan@gmail.com', '+33608020646', 'debutant', 'paris', 'Actif', 'inscription', 'Laurence Duval-Galvan', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('SABRIER', 'Pauline', 'p.sabrier@gmail.com', '+33683380268', 'debutant', 'paris', 'Actif', 'inscription', 'Pauline Sabrier', '', 'email partagé avec: Bruno GODEFROY', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('GUARINO', 'Gautier', 'gautier.guarino@gmail.com', '+33695566367', 'debutant', 'paris', 'Actif', 'inscription', 'Aïcha Fofana', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('GUÉRARD', 'Hantz', 'hantz5g@gmail.com', '+33783526744', 'debutant', 'paris', 'Actif', 'inscription', 'mélinda Marie-catherine', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('GUILLEMET', 'Zélie', 'zelie.guillemet@gmail.com', '+33659818157', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('LAHJAILY-CURT', 'Monique', 'monique.lahjailycma19@gmail.com', '+33604160481', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('LE BIHAN', 'Patrick', 'patrick_lebihan@yahoo.fr', '+33624664263', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('LETICHE', 'Angèle', 'angele.letiche@hotmail.fr', '+33645484343', 'debutant', 'paris', 'Actif', 'inscription', 'Felipe Diaz', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('LOMBREY', 'Elizabeth', 'elizabeth.lombrey@gmail.com', '+33685440350', 'debutant', 'paris', 'Actif', 'inscription', 'Louise Allix', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('LOUVET', 'Raphaël', 'louvet56@gmail.com', '+33764426728', 'debutant', 'paris', 'Actif', 'inscription', 'Raphael Louvet', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('MAY', 'Paul', 'paulmay3534@gmail.com', '+33757062826', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('MARIE-CATHERINE', 'Mélinda', 'melinda.mariecatherine@gmail.com', '+33662071300', 'debutant', 'paris', 'Actif', 'inscription', 'Hantz Guérard', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('MÉRIAUX', 'Alice', 'alice.meriaux@hotmail.fr', '+33606597417', 'debutant', 'paris', 'Actif', 'inscription', 'Alexandre Bezin', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('OTTONE', 'Ernesto', 'eottoneramirez@gmail.com', '+33788569598', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('PERES DE HAUTECLCOCQUE', 'Pamina', 'paminaetemmanuel@gmail.com', '+33671785168', 'debutant', 'paris', 'Actif', 'inscription', 'Emmanuel Peres de Hauteclcocque', '', 'email partagé avec: Emmanuel PERES DE HAUTECLOCQUE', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('PIKETTY', 'Benoit', 'benoit.piketty@gmail.com', '+33766857360', 'debutant', 'paris', 'Actif', 'inscription', 'Ameline Damy', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('POHIN', 'Arnaud', 'arnaud.pohin@gmail.com', '+33671716367', 'debutant', 'paris', 'Actif', 'inscription', 'Theodora PRASIADOU', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('PRASADOU', 'Theodora', 'prasiadoufr@gmail.com', '+33647371499', 'debutant', 'paris', 'Actif', 'inscription', 'Arnaud Pohin', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('RENÉ-CORAIL', 'Vincent', 'vreneco@yahoo.fr', '+33685771389', 'debutant', 'paris', 'Actif', 'inscription', 'Sophie VOUTEAU', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('SAN JUAN', 'Valérie', 'v.devincennes@gmail.com', '+33660105534', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('SANCHEZ', 'Mathieu', 'mathieu_sanchez01@yahoo.es', '+33614973355', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('SARAFIAN', 'Anouch', 'anouchjerome@outlook.fr', '+33618766458', 'debutant', 'paris', 'Actif', 'inscription', 'Jérôme Aucordier', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('SCHALCHLI', 'Ambroise', 'locvinchau@gmail.com', '+33651316958', 'debutant', 'paris', 'Actif', 'inscription', 'Clothilde Chauvin', '', 'email partagé avec: Clothilde SCHALCHLI', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('SCHALLER', 'Justine', 'schaller.justine93@gmail.com', '+33604045786', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('SQUARCIONI', 'Gabrielle', 'squargab3@gmail.com', '+33619583864', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('THIREAU', 'Sandrine', 'sandrine.thireau@hotmail.fr', '+33607034947', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('VOUTEAU SOPHIE', 'Vouteau', 'svouteau@gmail.com', '+33666640752', 'debutant', 'paris', 'Actif', 'inscription', 'vincent RENE-CORAIL', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('ZAMITI', 'Sana', 'sanazamiti81@gmail.com', '+33659009030', 'debutant', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('ALVARO', 'Maria', 'unairdeclope@gmail.com', '+33658172211', 'intermediaire', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('CASTRO', 'Svetlana', 'castrosvetlana@gmail.com', '+33769230035', 'intermediaire', 'paris', 'Actif', 'inscription', 'Vlad Vasiliu', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('CHASSONNERIE', 'Thomas', 'tchassonnerie@gmail.com', '+33679717093', 'intermediaire', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('CUNIN', 'Aline', 'cuninaline@hotmail.fr', '+33643185460', 'intermediaire', 'paris', 'Actif', 'inscription', 'Nicolas Targa', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('CUSSAGUET', 'Régine', 'regine.cussaguet@gmail.com', '+33608458573', 'intermediaire', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('DUTOIT', 'Maria', 'mariekeduursma@wanadoo.fr', '+33681880262', 'intermediaire', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('LAROCHE', 'Nicolas', 'larochenicolas@icloud.com', '+33651979837', 'intermediaire', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('LHUISSIER', 'Maud', 'maud.lhuissier@gmail.com', '+33670380316', 'intermediaire', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('lefebvre', 'Boris', 'lefebvreboris222@gmail.com', '+33666995629', 'intermediaire', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('MADELAINE', 'Damien', 'damien.madelaine@orange.fr', '+33603803088', 'intermediaire', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('Madignier', 'Sophie', 's.madignier@gmail.com', '+33630916762', 'intermediaire', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('ROUDAKOVA', 'Olga', 'olga.ru@free.fr', '+33660935307', 'intermediaire', 'paris', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('VASILIU', 'Vlad', 'vvasiliu@gmail.com', '+33687858105', 'intermediaire', 'paris', 'Actif', 'inscription', 'Svetlana Castro', '', 'cours: paris + vincennes', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('VORMS', 'Sandrine', 'lesvorms@noos.fr', '+33615466973', 'intermediaire', 'paris', 'Actif', 'inscription', 'Bertrand VORMS', '', 'email partagé avec: Bertrand VORMS', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('AMSALLEM', 'Jacques', 'jacquesamsallem@yahoo.fr', '+33675718775', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('ARCHAMBAULT', 'Maryse', 'a.maryz@laposte.net', '+33679660998', 'debutant', 'vincennes', 'Actif', 'inscription', 'Robert Archambault', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('ARCHAMBAULT', 'Robert', 'robert.archambault@laposte.net', '+33682816626', 'debutant', 'vincennes', 'Actif', 'inscription', 'Maryse Archambault', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BARRÉ', 'Louswann', 'lb7.barre@gmail.com', '+33749429738', 'debutant', 'vincennes', 'Actif', 'inscription', 'Enzo MELE', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BLUM', 'Karine', 'karin.blum1968@gmail.com', '+33664706606', 'debutant', 'vincennes', 'Actif', 'inscription', 'Eric Blum', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BLUM', 'Eric', 'ericblum1964jalz@gmail.com', '+33673512327', 'debutant', 'vincennes', 'Actif', 'inscription', 'Karine Blum', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BOVE', 'Annalisa', 'alisabove@yahoo.it', '+33637487125', 'debutant', 'vincennes', 'Actif', 'inscription', 'Vlodja BRUSA', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BRUSA', 'Vlodja', 'vlodja.brusa@laposte.net', '+33681421520', 'debutant', 'vincennes', 'Actif', 'inscription', 'Annalisa BOVE', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('CARBO', 'Michael', 'carbomichael1@gmail.com', '+33762203832', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('DELY', 'Didier', 'didier.dely@me.com', '+33685741954', 'debutant', 'vincennes', 'Actif', 'inscription', 'Isabelle Dely', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('DELY', 'Isabelle', 'isabelle.dely@cnda.juradm.fr', '+33681166957', 'debutant', 'vincennes', 'Actif', 'inscription', 'Didier Dely', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('DU BOUCHER', 'Marie', 'marie.duboucher@gmail.com', '+33674970324', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('DUPLESSI', 'Olivier', 'olivier.duplessi@gmail.com', '+33621015173', 'debutant', 'vincennes', 'Actif', 'inscription', 'Sara Kalantari', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('GALLIOT LAPOULE', 'Gil', 'gilgalliot10@gmail.com', '+33610254826', 'debutant', 'vincennes', 'Actif', 'inscription', 'Olympe PIRO', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('GARCÈS', 'Frédéric', 'frederic.andre@hotmail.fr', '+33663090914', 'debutant', 'vincennes', 'Actif', 'inscription', 'Emma Spiesser', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('KALANTARI', 'Sara', 'avajik@gmail.com', '+33652826906', 'debutant', 'vincennes', 'Actif', 'inscription', 'Olivier Duplessi', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('Konopka', 'Antoine', 'antoine.konopka@gmail.com', '+33647000285', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('LANDAIS', 'Maud', 'maud.landais@gmail.com', '+33625574328', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('MARTIN', 'Alina Diana', 'dianamartin_diet17@yahoo.fr', '+33677442860', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('MARZILLI', 'Joëlle', 'jmarzilli@hotmail.fr', '+33616731677', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('MELE', 'Enzo', 'ludivinedias@yahoo.fr', '+33671695656', 'debutant', 'vincennes', 'Actif', 'inscription', 'Louswann Barré', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('MICKAEL', 'Timsit', 'mickael@giegama.com', '+33668463057', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('MOREAU', 'Annette Viviane', 'rajaonavivi@gmail.com', '+33670416101', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('OUDOT', 'Filipe', 'oc.filipe@outlook.com', '+33683430648', 'debutant', 'vincennes', 'Actif', 'inscription', 'Camille Prieux', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('PICOT', 'Fabienne', 'fabienne.picot@free.fr', '+33608349966', 'debutant', 'vincennes', 'Actif', 'inscription', 'Jean Michel ROUX', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('PIERRE-JUSTIN', 'Karl', 'kpierrejustin@gmail.com', '+33616101844', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('PILARD', 'Pauline', 'paulinepilard@gmail.com', '+33686459726', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('PIRO', 'Olympe', 'olympe.piro@hotmail.fr', '+33611282555', 'debutant', 'vincennes', 'Actif', 'inscription', 'gil GALLIOT', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('PONTON', 'Lionel', 'lionelponton@gmail.com', '+33648153928', 'debutant', 'vincennes', 'Actif', 'inscription', 'Lionel Ponton', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('PRIEUX', 'Camille', 'camille.prieux20@gmail.com', '+33763339399', 'debutant', 'vincennes', 'Actif', 'inscription', 'Filipe Oudot', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('RIFFE STERN', 'Sylvain', 'sylvain.riffe@gmail.com', '+33767077772', 'debutant', 'vincennes', 'Actif', 'inscription', 'Anne-Sylvie STERN RIFFE', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('ROUX', 'Jean Michel', 'jean_michel_roux@hotmail.fr', '+33614305756', 'debutant', 'vincennes', 'Actif', 'inscription', 'Jean Michel Roux', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('SABOURIN', 'Florent', 'sabourin.florent1@gmail.com', '+33688325716', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('SPIESSER', 'Emma', 'spiesseremma@gmail.com', '+33643188979', 'debutant', 'vincennes', 'Actif', 'inscription', 'Frederic Garcès', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('STERN RIFFE', 'Anne-Sylvie', 'anne-sylvie.stern@neuf.fr', '+33782671339', 'debutant', 'vincennes', 'Actif', 'inscription', 'Sylvain RIFFE STERN', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('TORTAJADA', 'Stéphane', 'stephane.tortajada45@gmail.com', '+33607398354', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('TYSMAN', 'David', 'tango@hellodavid.me', '+33664268533', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('VILLARD', 'Renata', 'renata@bbm74.com', '+33607511241', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('WAWROWSKA', 'Anna', 'anekgda@gmail.com', '+33670097855', 'debutant', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('AUDIGIER', 'François', 'fpetetin050@gmail.com', '+33620887558', 'intermediaire', 'vincennes', 'Actif', 'inscription', 'Fabienne AUDIGIER', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('AUDIGIER', 'Fabienne', 'faudigier@gmail.com', '+33662708489', 'intermediaire', 'vincennes', 'Actif', 'inscription', 'FRANCOIS AUDIGIER', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BARRECA', 'Claude', 'claudebarreca@yahoo.fr', '+33687274278', 'intermediaire', 'vincennes', 'Actif', 'inscription', 'Corinne Stival', '', '', '2025-2026', NULL, NULL, 0, 10, 'Nouvelle carte', TRUE),
  ('BELKHIR', 'Sophia', 'sophia.belkhir@laposte.net', '+33650011409', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BESSAA', 'Samia', 'samia.bessaa2@gmail.com', '+33781082724', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BREUIL', 'Marie-Anne', 'marieanne.breuil@laposte.net', '+33622980750', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('CALISIR', 'Clarisse', 'oceaneclaris@hotmail.fr', '+33618363817', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('CHAUMONT', 'Jerome', 'hyeronimus.ludovicus@gmail.com', '+33772279836', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('chavanne', 'Violaine', 'viochavanne@free.fr', '+33662356818', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('Cissey', 'Gérard', 'gcisseyconsulting@gmail.com', '+33698208727', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('COURTOUX', 'Laure', 'laure.courtoux@free.fr', '+33643377824', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('DACHAUD', 'Lionel', 'lionel@paradisiaque.net', '+33663565440', 'intermediaire', 'vincennes', 'Actif', 'inscription', 'Carla Vicentini', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('DEBAS', 'Thierry', 'thierry.debas@wanadoo.fr', '+33633856977', 'intermediaire', 'vincennes', 'Actif', 'inscription', 'Thierry DEBAS', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('DEBAS', 'Véronique', 'veronique.ollivierdebas@yahoo.fr', '+33670652364', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('DESGRAUPES', 'Katia', 'kdesgraupes@gmail.com', '+33613729396', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('DESTIVAL', 'Isabelle', 'isabelle.destival@orange.fr', '+33613424754', 'intermediaire', 'vincennes', 'Actif', 'inscription', 'Vincent Destival', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('DESTIVAL', 'Vincent', 'vincent.destival@orange.fr', '+33668228035', 'intermediaire', 'vincennes', 'Actif', 'inscription', 'Isabelle DESTIVAL', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('DUTOIT', 'Marc', 'marc.dutoit@wanadoo.fr', '+33686433705', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('GEORGALI', 'Maria', 'mariageorgali@gmail.com', '+33699205111', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('GÉRÔME', 'Alban', 'albangerome75@gmail.com', '+33662425392', 'intermediaire', 'vincennes', 'Actif', 'inscription', 'Sandrine Pitarque', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('GOURDON', 'Annette', 'a.gourdon2@wanadoo.fr', '+33668782000', 'intermediaire', 'vincennes', 'Actif', 'inscription', 'Vlad Vasiliu', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('GRANIER', 'Pierre', 'gpierre94@yahoo.fr', '+33668797427', 'intermediaire', 'vincennes', 'Actif', 'inscription', 'Marie-Hélène Granier', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('GRANIER', 'Marie-Hélène', 'mh.granier@gmail.com', '+33630362488', 'intermediaire', 'vincennes', 'Actif', 'inscription', 'Pierre Granier', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('HENRY', 'Gilles', 'mesachats2016@outlook.com', '+33687743071', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('HERVIEUX', 'Cyril', 'cyril.hervieux@hotmail.com', '+33667930814', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('JASKOWSKA', 'Elisabeth', 'elisabeth.jaskowska@gmail.com', '+33695304878', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('KARADJOV', 'Nikolay', 'maria.karadjova@dentons.com', '+33662331720', 'intermediaire', 'vincennes', 'Actif', 'inscription', 'Maria Karadjova', '', 'email partagé avec: Maria KARADJOVA', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('KIRMIZIGUL', 'Cihan', 'cihan1510@gmail.com', '+33605784812', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('LEVERT', 'Pascal', 'levert.pascal@sfr.fr', '+33610193567', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('PENANHOAT', 'Olivier', 'openanhoat@wanadoo.fr', '+33651469563', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('PHILIPPART', 'Raynald', 'rphilippart@laposte.net', '+33670752153', 'intermediaire', 'vincennes', 'Actif', 'inscription', 'odile PHILIPPART', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('PHILIPPART', 'Odile', 'od.philippart@laposte.net', '+33685867421', 'intermediaire', 'vincennes', 'Actif', 'inscription', 'raynald PHILIPPART', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('PINO-FARGIER', 'Soledad', 'soledadsoft@gmail.com', '+33659708008', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('RAMPIN', 'Christian', 'kinourampin@gmail.com', '+33627846856', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('REBOURS', 'Pascale', 'pascale.rebours@neuf.fr', '+33619827250', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('RIPAMONTI', 'Julien', 'julien_ripa@hotmail.fr', '+33670380902', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('SALAS', 'Luis', 'lasalma@yahoo.fr', '+33612620468', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('SALQUES', 'Valérie', 'valeriesalques@yahoo.fr', '+33620335215', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('SINSOU', 'Christophe', 'christophe.sinsou@gmail.com', '+33688062946', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('STIVAL', 'Corinne', 'corinne.stival@gmail.com', '+33618395194', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('VICENTINI', 'Carla', 'vicentini.carla@gmail.com', '+33647900037', 'intermediaire', 'vincennes', 'Actif', 'inscription', 'Lionel Dachaud', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('VONG', 'Kristyane', 'kristyane@yahoo.com', '+33650639852', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('WARNOD', 'Raymond', 'rwarnod@yahoo.fr', '+33652163857', 'intermediaire', 'vincennes', 'Actif', 'inscription', '', '', '', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('ANTOINE', 'Baudoux', 'antoinej.baudoux@gmail.com', '+33607063758', '', '', 'Actif', 'inscription', '', '', 'yoga: hatha', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BEZZAH', 'Noham', 'bezzahnoham@gmail.com', '+33658352018', '', '', 'Actif', 'inscription', '', '', 'yoga: hatha', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BILLOT', 'Sandrine', 'sandrine_billot@orange.fr', '+33626820835', '', '', 'Actif', 'inscription', '', '', 'yoga: hatha + yin', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BOISSEAUX', 'Pascale', 'boisseaux.pascale@gmail.com', '+33603549110', '', '', 'Actif', 'inscription', '', '', 'yoga: hatha', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BORDIN', 'Noelle', 'nbordin@free.fr', '+33664550340', '', '', 'Actif', 'inscription', '', '', 'yoga: hatha', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('CANTON-PONT', 'Claude', 'claudecanton@yahoo.fr', '+33625702853', '', '', 'Actif', 'inscription', '', '', 'yoga: hatha', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('CLAUDE', 'Marylène', 'marylene.claude8@orange.fr', '+33673183061', '', '', 'Actif', 'inscription', '', '', 'yoga: hatha', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('DAGANY', 'Julia', 'julia.dagany@orange.fr', '+33608467272', '', '', 'Actif', 'inscription', '', '', 'yoga: hatha', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('LEGUAY', 'Daniele', 'daniele.leguay@yahoo.fr', '+33618945741', '', '', 'Actif', 'inscription', '', '', 'yoga: hatha', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('MILBERGUE', 'Chantal', 'chantemil93@gmail.com', '+33622097617', '', '', 'Actif', 'inscription', '', '', 'yoga: hatha', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('SALESNE', 'Camille', 'camille.salesne@gmail.com', '+33612876234', '', '', 'Actif', 'inscription', '', '', 'yoga: hatha', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BEDEZ', 'Bertrand', 'bertrand.bedez@yahoo.com', '+33766823672', '', '', 'Actif', 'inscription', '', '', 'yoga: yin', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BENOISTEL', 'Marie-Laure', 'ml.benoistel@gmail.com', '+33781412935', '', '', 'Actif', 'inscription', '', '', 'yoga: yin', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BENSAMOUN', 'Danielle', 'bensamoundanielle@gmail.com', '+33634483562', '', '', 'Actif', 'inscription', '', '', 'yoga: yin', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BLOCH', 'Myriam', 'mymybloch@gmail.com', '+33672912651', '', '', 'Actif', 'inscription', '', '', 'yoga: yin', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('BOUKOBZA', 'Eva', 'evaboukobza@gmail.com', '+33629139095', '', '', 'Actif', 'inscription', '', '', 'yoga: yin', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('DEMOUY', 'Marianne', 'demouy.jm@orange.fr', '+33684989290', '', '', 'Actif', 'inscription', '', '', 'yoga: yin', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('GUILLOT', 'Jean-Claude', 'jean-claude.guillot14@orange.fr', '+33685958211', '', '', 'Actif', 'inscription', '', '', 'yoga: yin', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('JORDAN', 'Christine', 'christijor@yahoo.fr', '+33607819693', '', '', 'Actif', 'inscription', '', '', 'yoga: yin', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('LESSERTISSEUR', 'Alexandre', 'alexandre.lessertisseur@gmail.com', '+33685668097', '', '', 'Actif', 'inscription', '', '', 'yoga: yin', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE),
  ('QUILES', 'Corinne', 'cquiles@hotmail.fr', '+33684950515', '', '', 'Actif', 'inscription', '', '', 'yoga: yin', '2025-2026', NULL, NULL, 0, 0, 'Forfait', TRUE);


-- 2. INSCRIPTIONS COURS (167 lignes)
-- ----------------------------------------------------------------
INSERT INTO inscriptions_cours
  (prenom, nom, email, niveau, ville, type, saison, statut,
   partenaire, email_partenaire)
VALUES
  ('Hicham', 'ALAMI', 'hicham.a85@icloud.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Louise', 'ALLIX', 'allix.louise.l@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Elizabeth Lombrey', ''),
  ('Serban', 'ANGHEL', 'serbanghel@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Jérôme', 'AUCORDIER', 'jaucordier@colibri-asso.fr', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Anouch SARAFIAN', ''),
  ('Christophe', 'AYAD', 'christophe.ayad@gmail.com', 'debutant', 'paris', 'forfait', '2025-2026', 'inscrit', 'Olivia Colo', ''),
  ('Alexandre', 'BEZIN', 'alexandre-bezin@orange.fr', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Thouraya', 'BOUAZIZ', 'bouazizthou@live.fr', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Henry', 'BUTASH', 'hbutash@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Irmak Nacak', ''),
  ('Rémy', 'CARDINET', 'remy.cardinet+tango@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Florence', 'CASTAGNOS', 'flocastagnos@yahoo.fr', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Florence', 'CASTAGNOS', 'flocastagnos@yahoo.fr', 'intermediaire', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Olivia', 'COLO', 'oliviacolo@gmail.com', 'debutant', 'paris', 'forfait', '2025-2026', 'inscrit', 'Christophe Ayad', ''),
  ('Clara', 'COSENTINO', 'claracosentino1306@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Ameline', 'DAMY', 'ameline.damy@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Benoît Piketty', ''),
  ('Felipe', 'DIAZ', 'felipea.diazp@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Angèle Diaz', ''),
  ('Laurence', 'DUVAL-GALVAN', 'lgdg5924@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Jorge Galvan', ''),
  ('Marine', 'EYRAUD', 'marineeyraud@yahoo.fr', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Hugo', 'FIGUEREDO', 'salvaje91@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'ANAIS GOSSELIN', ''),
  ('Aïcha', 'FOFANA', 'f.aicha@yahoo.fr', 'debutant', 'paris', 'forfait', '2025-2026', 'inscrit', 'Guarino Gautier', ''),
  ('Nicolas', 'FONTAINE', 'nicolas.fontaine@gmx.com', 'debutant', 'paris', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Jorge', 'GALVAN', 'georges.galvan@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Laurence Duval-Galvan', ''),
  ('Pauline', 'SABRIER', 'p.sabrier@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Pauline Sabrier', ''),
  ('Gautier', 'GUARINO', 'gautier.guarino@gmail.com', 'debutant', 'paris', 'forfait', '2025-2026', 'inscrit', 'Aïcha Fofana', ''),
  ('Hantz', 'GUÉRARD', 'hantz5g@gmail.com', 'debutant', 'paris', 'forfait', '2025-2026', 'inscrit', 'mélinda Marie-catherine', ''),
  ('Zélie', 'GUILLEMET', 'zelie.guillemet@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Monique', 'LAHJAILY-CURT', 'monique.lahjailycma19@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Patrick', 'LE BIHAN', 'patrick_lebihan@yahoo.fr', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Angèle', 'LETICHE', 'angele.letiche@hotmail.fr', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Felipe Diaz', ''),
  ('Elizabeth', 'LOMBREY', 'elizabeth.lombrey@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Louise Allix', ''),
  ('Raphaël', 'LOUVET', 'louvet56@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Raphael Louvet', ''),
  ('Paul', 'MAY', 'paulmay3534@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Mélinda', 'MARIE-CATHERINE', 'melinda.mariecatherine@gmail.com', 'debutant', 'paris', 'forfait', '2025-2026', 'inscrit', 'Hantz Guérard', ''),
  ('Alice', 'MÉRIAUX', 'alice.meriaux@hotmail.fr', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Alexandre Bezin', ''),
  ('Ernesto', 'OTTONE', 'eottoneramirez@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Pamina', 'PERES DE HAUTECLCOCQUE', 'paminaetemmanuel@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Emmanuel Peres de Hauteclcocque', ''),
  ('Benoit', 'PIKETTY', 'benoit.piketty@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Ameline Damy', ''),
  ('Arnaud', 'POHIN', 'arnaud.pohin@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Theodora PRASIADOU', ''),
  ('Theodora', 'PRASADOU', 'prasiadoufr@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Arnaud Pohin', ''),
  ('Vincent', 'RENÉ-CORAIL', 'vreneco@yahoo.fr', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Sophie VOUTEAU', ''),
  ('Valérie', 'SAN JUAN', 'v.devincennes@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Mathieu', 'SANCHEZ', 'mathieu_sanchez01@yahoo.es', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Anouch', 'SARAFIAN', 'anouchjerome@outlook.fr', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'Jérôme Aucordier', ''),
  ('Ambroise', 'SCHALCHLI', 'locvinchau@gmail.com', 'debutant', 'paris', 'forfait', '2025-2026', 'inscrit', 'Clothilde Chauvin', ''),
  ('Justine', 'SCHALLER', 'schaller.justine93@gmail.com', 'debutant', 'paris', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Gabrielle', 'SQUARCIONI', 'squargab3@gmail.com', 'debutant', 'paris', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Sandrine', 'THIREAU', 'sandrine.thireau@hotmail.fr', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Vouteau', 'VOUTEAU SOPHIE', 'svouteau@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', 'vincent RENE-CORAIL', ''),
  ('Sana', 'ZAMITI', 'sanazamiti81@gmail.com', 'debutant', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Maria', 'ALVARO', 'unairdeclope@gmail.com', 'intermediaire', 'paris', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Svetlana', 'CASTRO', 'castrosvetlana@gmail.com', 'intermediaire', 'paris', 'forfait', '2025-2026', 'inscrit', 'Vlad Vasiliu', ''),
  ('Thomas', 'CHASSONNERIE', 'tchassonnerie@gmail.com', 'intermediaire', 'paris', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Aline', 'CUNIN', 'cuninaline@hotmail.fr', 'intermediaire', 'paris', 'carte', '2025-2026', 'inscrit', 'Nicolas Targa', ''),
  ('Régine', 'CUSSAGUET', 'regine.cussaguet@gmail.com', 'intermediaire', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Maria', 'DUTOIT', 'mariekeduursma@wanadoo.fr', 'intermediaire', 'paris', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Nicolas', 'LAROCHE', 'larochenicolas@icloud.com', 'intermediaire', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Maud', 'LHUISSIER', 'maud.lhuissier@gmail.com', 'intermediaire', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Boris', 'lefebvre', 'lefebvreboris222@gmail.com', 'intermediaire', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Damien', 'MADELAINE', 'damien.madelaine@orange.fr', 'intermediaire', 'paris', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Sophie', 'Madignier', 's.madignier@gmail.com', 'intermediaire', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Olga', 'ROUDAKOVA', 'olga.ru@free.fr', 'intermediaire', 'paris', 'carte', '2025-2026', 'inscrit', '', ''),
  ('Vlad', 'VASILIU', 'vvasiliu@gmail.com', 'intermediaire', 'paris', 'carte', '2025-2026', 'inscrit', 'Svetlana Castro', ''),
  ('Vlad', 'VASILIU', 'vvasiliu@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Annette Gnourdo', ''),
  ('Sandrine', 'VORMS', 'lesvorms@noos.fr', 'intermediaire', 'paris', 'forfait', '2025-2026', 'inscrit', 'Bertrand VORMS', ''),
  ('Jacques', 'AMSALLEM', 'jacquesamsallem@yahoo.fr', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Maryse', 'ARCHAMBAULT', 'a.maryz@laposte.net', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Robert Archambault', ''),
  ('Robert', 'ARCHAMBAULT', 'robert.archambault@laposte.net', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Maryse Archambault', ''),
  ('Louswann', 'BARRÉ', 'lb7.barre@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Enzo MELE', ''),
  ('Karine', 'BLUM', 'karin.blum1968@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Eric Blum', ''),
  ('Eric', 'BLUM', 'ericblum1964jalz@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Karine Blum', ''),
  ('Annalisa', 'BOVE', 'alisabove@yahoo.it', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Vlodja BRUSA', ''),
  ('Vlodja', 'BRUSA', 'vlodja.brusa@laposte.net', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Annalisa BOVE', ''),
  ('Michael', 'CARBO', 'carbomichael1@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Didier', 'DELY', 'didier.dely@me.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Isabelle Dely', ''),
  ('Isabelle', 'DELY', 'isabelle.dely@cnda.juradm.fr', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Didier Dely', ''),
  ('Marie', 'DU BOUCHER', 'marie.duboucher@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Olivier', 'DUPLESSI', 'olivier.duplessi@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Sara Kalantari', ''),
  ('Gil', 'GALLIOT LAPOULE', 'gilgalliot10@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Olympe PIRO', ''),
  ('Frédéric', 'GARCÈS', 'frederic.andre@hotmail.fr', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Emma Spiesser', ''),
  ('Sara', 'KALANTARI', 'avajik@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Olivier Duplessi', ''),
  ('Antoine', 'Konopka', 'antoine.konopka@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Maud', 'LANDAIS', 'maud.landais@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Alina Diana', 'MARTIN', 'dianamartin_diet17@yahoo.fr', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Joëlle', 'MARZILLI', 'jmarzilli@hotmail.fr', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Enzo', 'MELE', 'ludivinedias@yahoo.fr', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Louswann Barré', ''),
  ('Timsit', 'MICKAEL', 'mickael@giegama.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Annette Viviane', 'MOREAU', 'rajaonavivi@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Filipe', 'OUDOT', 'oc.filipe@outlook.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Camille Prieux', ''),
  ('Fabienne', 'PICOT', 'fabienne.picot@free.fr', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Jean Michel ROUX', ''),
  ('Karl', 'PIERRE-JUSTIN', 'kpierrejustin@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Pauline', 'PILARD', 'paulinepilard@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Olympe', 'PIRO', 'olympe.piro@hotmail.fr', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'gil GALLIOT', ''),
  ('Lionel', 'PONTON', 'lionelponton@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Lionel Ponton', ''),
  ('Camille', 'PRIEUX', 'camille.prieux20@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Filipe Oudot', ''),
  ('Sylvain', 'RIFFE STERN', 'sylvain.riffe@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Anne-Sylvie STERN RIFFE', ''),
  ('Jean Michel', 'ROUX', 'jean_michel_roux@hotmail.fr', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Jean Michel Roux', ''),
  ('Florent', 'SABOURIN', 'sabourin.florent1@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Emma', 'SPIESSER', 'spiesseremma@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Frederic Garcès', ''),
  ('Anne-Sylvie', 'STERN RIFFE', 'anne-sylvie.stern@neuf.fr', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Sylvain RIFFE STERN', ''),
  ('Stéphane', 'TORTAJADA', 'stephane.tortajada45@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('David', 'TYSMAN', 'tango@hellodavid.me', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Renata', 'VILLARD', 'renata@bbm74.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Anna', 'WAWROWSKA', 'anekgda@gmail.com', 'debutant', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('François', 'AUDIGIER', 'fpetetin050@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Fabienne AUDIGIER', ''),
  ('Fabienne', 'AUDIGIER', 'faudigier@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'FRANCOIS AUDIGIER', ''),
  ('Claude', 'BARRECA', 'claudebarreca@yahoo.fr', 'intermediaire', 'vincennes', 'carte', '2025-2026', 'inscrit', 'Corinne Stival', ''),
  ('Sophia', 'BELKHIR', 'sophia.belkhir@laposte.net', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Samia', 'BESSAA', 'samia.bessaa2@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Marie-Anne', 'BREUIL', 'marieanne.breuil@laposte.net', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Clarisse', 'CALISIR', 'oceaneclaris@hotmail.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Jerome', 'CHAUMONT', 'hyeronimus.ludovicus@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Violaine', 'chavanne', 'viochavanne@free.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Gérard', 'Cissey', 'gcisseyconsulting@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Laure', 'COURTOUX', 'laure.courtoux@free.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Lionel', 'DACHAUD', 'lionel@paradisiaque.net', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Carla Vicentini', ''),
  ('Thierry', 'DEBAS', 'thierry.debas@wanadoo.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Thierry DEBAS', ''),
  ('Véronique', 'DEBAS', 'veronique.ollivierdebas@yahoo.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Katia', 'DESGRAUPES', 'kdesgraupes@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Isabelle', 'DESTIVAL', 'isabelle.destival@orange.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Vincent Destival', ''),
  ('Vincent', 'DESTIVAL', 'vincent.destival@orange.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Isabelle DESTIVAL', ''),
  ('Marc', 'DUTOIT', 'marc.dutoit@wanadoo.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Maria', 'GEORGALI', 'mariageorgali@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Alban', 'GÉRÔME', 'albangerome75@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Sandrine Pitarque', ''),
  ('Annette', 'GOURDON', 'a.gourdon2@wanadoo.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Vlad Vasiliu', ''),
  ('Pierre', 'GRANIER', 'gpierre94@yahoo.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Marie-Hélène Granier', ''),
  ('Marie-Hélène', 'GRANIER', 'mh.granier@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Pierre Granier', ''),
  ('Gilles', 'HENRY', 'mesachats2016@outlook.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Cyril', 'HERVIEUX', 'cyril.hervieux@hotmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Elisabeth', 'JASKOWSKA', 'elisabeth.jaskowska@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Nikolay', 'KARADJOV', 'maria.karadjova@dentons.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Maria Karadjova', ''),
  ('Cihan', 'KIRMIZIGUL', 'cihan1510@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Pascal', 'LEVERT', 'levert.pascal@sfr.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Olivier', 'PENANHOAT', 'openanhoat@wanadoo.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Raynald', 'PHILIPPART', 'rphilippart@laposte.net', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'odile PHILIPPART', ''),
  ('Odile', 'PHILIPPART', 'od.philippart@laposte.net', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'raynald PHILIPPART', ''),
  ('Soledad', 'PINO-FARGIER', 'soledadsoft@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Christian', 'RAMPIN', 'kinourampin@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Pascale', 'REBOURS', 'pascale.rebours@neuf.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Julien', 'RIPAMONTI', 'julien_ripa@hotmail.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Luis', 'SALAS', 'lasalma@yahoo.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Valérie', 'SALQUES', 'valeriesalques@yahoo.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Christophe', 'SINSOU', 'christophe.sinsou@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Corinne', 'STIVAL', 'corinne.stival@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Carla', 'VICENTINI', 'vicentini.carla@gmail.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', 'Lionel Dachaud', ''),
  ('Kristyane', 'VONG', 'kristyane@yahoo.com', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Raymond', 'WARNOD', 'rwarnod@yahoo.fr', 'intermediaire', 'vincennes', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Baudoux', 'ANTOINE', 'antoinej.baudoux@gmail.com', 'hatha', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Noham', 'BEZZAH', 'bezzahnoham@gmail.com', 'hatha', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Sandrine', 'BILLOT', 'sandrine_billot@orange.fr', 'hatha', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Sandrine', 'BILLOT', 'sandrine_billot@orange.fr', 'yin', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Pascale', 'BOISSEAUX', 'boisseaux.pascale@gmail.com', 'hatha', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Noelle', 'BORDIN', 'nbordin@free.fr', 'hatha', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Claude', 'CANTON-PONT', 'claudecanton@yahoo.fr', 'hatha', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Marylène', 'CLAUDE', 'marylene.claude8@orange.fr', 'hatha', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Julia', 'DAGANY', 'julia.dagany@orange.fr', 'hatha', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Daniele', 'LEGUAY', 'daniele.leguay@yahoo.fr', 'hatha', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Chantal', 'MILBERGUE', 'chantemil93@gmail.com', 'hatha', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Camille', 'SALESNE', 'camille.salesne@gmail.com', 'hatha', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Bertrand', 'BEDEZ', 'bertrand.bedez@yahoo.com', 'yin', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Marie-Laure', 'BENOISTEL', 'ml.benoistel@gmail.com', 'yin', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Danielle', 'BENSAMOUN', 'bensamoundanielle@gmail.com', 'yin', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Myriam', 'BLOCH', 'mymybloch@gmail.com', 'yin', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Eva', 'BOUKOBZA', 'evaboukobza@gmail.com', 'yin', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Marianne', 'DEMOUY', 'demouy.jm@orange.fr', 'yin', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Jean-Claude', 'GUILLOT', 'jean-claude.guillot14@orange.fr', 'yin', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Christine', 'JORDAN', 'christijor@yahoo.fr', 'yin', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Alexandre', 'LESSERTISSEUR', 'alexandre.lessertisseur@gmail.com', 'yin', '', 'forfait', '2025-2026', 'inscrit', '', ''),
  ('Corinne', 'QUILES', 'cquiles@hotmail.fr', 'yin', '', 'forfait', '2025-2026', 'inscrit', '', '');


COMMIT;
